version: "3.3"
services:
  rabbitmq_server:
    image: rabbitmq:management
    ports:
      - 5672:5672/tcp
      - 15672:15672/tcp
    container_name: "rabbitmq_server"
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - $PWD/rabbitmq:var/lib/rabbitmq
      - $PWD/rabbitmq:/var/log/rabbitmq
    networks:
      - myweb

networks:
  myweb:
    driver: bridge
