version: "3.3"
services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    privileged: true
    volumes:
      - $PWD/mariadb/log:/var/log/mysql
      - $PWD/mariadb/conf/my.cnf:/etc/mysql/my.cnf
      - $PWD/mariadb/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: "andy"
      MYSQL_PASS: "123456"
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_general_ci",
        "--max_connections=3000",
      ]
    networks:
      - myweb

networks:
  myweb:
    driver: bridge
